require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '10.0'

target 'MoverWarehouse' do
  # Pods for MoverWarehouse
  config = use_native_modules!

  use_react_native!(:path => config["reactNativePath"])

  # REACT-NATIVE-PERMISSIONS
  permissions_path = '../node_modules/react-native-permissions/ios'
  pod 'Permission-Camera', :path => "#{permissions_path}/Camera.podspec"

  # REACT-NATIVE-FETCH-BLOB
  pod 'rn-fetch-blob', :path => '../node_modules/rn-fetch-blob'

  # REACT-NATIVE-CAMERA
  pod 'react-native-camera', path: '../node_modules/react-native-camera', subspecs: [
  'TextDetector',
  # 'FaceDetectorMLKit',
  'BarcodeDetectorMLKit'
]

  # FIREBASE V5
  pod 'Firebase/Analytics'
  pod 'Firebase/Messaging', '~> 6.13.0'



  target 'MoverWarehouseTests' do
    inherit! :complete
    # Pods for testing
  end

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable these next few lines.
  use_flipper!
  post_install do |installer|
    flipper_post_install(installer)
  end
end

target 'MoverWarehouse-tvOS' do
  # Pods for MoverWarehouse-tvOS

  target 'MoverWarehouse-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end
end
